### ISSUE TITLE
Unnecessary requirement for acl_operation in module kafka_acls

### ISSUE THREAD

**Issue by david-freistrom** [StephenSorriaux/ansible-kafka-admin#124]
## Expected Behavior

Delete all ACLs for a specific Topic

## Actual Behavior

acl_operation is a required attributes for kafka_acls module which prevent to delete all ACLs for a specific Topic

## Play to Reproduce the Problem

```yaml
- name: Delete all ACLs for a Topic in Kafka
  StephenSorriaux.ansible_kafka_admin.kafka_acl.kafka_acls:
    bootstrap_servers: "{{ lookup('ENV', 'KAFKA_BOOTSTRAP_SERVERS') }}"
    acls:
      - acl_resource_type: 'topic'
        name: 'test'
        state: 'absent'
```

## Logs from the play with Ansible in debug mode

```acl_operation is required```

This error is explicitly thrown here but in general not declared as an required attribute. I think its an unnecessary line of code.

https://github.com/StephenSorriaux/ansible-kafka-admin/blob/547ff8c38b7383bdc3f4fafb1d303d28d1c484ae/module_utils/kafka_lib_acl.py#L57

Kafka has not that requirement.

## Specifications

  - Library version: 0.15.1
  - Result of `pip list` command: 
  - Kafka version: 2.8.1
  - Python version: 3.8
  - OS:  5.15.12-100.fc34.x86_64
