### ISSUE TITLE
kafka 2.1 not work 

### ISSUE THREAD

**Issue by chris93111** [StephenSorriaux/ansible-kafka-admin#41]
hello 

i would like create topics with kafka 2.1 but is not work  he could not connect to broker 

Cannot determine a controller for your current Kafka server. Is your Kafka server running and available on '10.210.6.104' with security protocol 'PLAINTEXT'?"

- name: create topics
  kafka_topic:
    resource: "topic"
    api_version: "2.3.0"
    name: "{{item.name}}"
    partitions: "{{item.partitions}}"
    replica_factor: "{{item.replication_factor}}"
    state: "present"
    zookeeper: "localhost:2181"
    security_protocol: 'PLAINTEXT'
    options:
      retention.ms: "{{item.retention}}"
      min.insync.replicas: "{{item.min_replicas}}"
      flush.messages: "{{item.flush_messages}}"
    bootstrap_servers: "{{ hostvars[inventory_hostname]['ansible_eth0']['ipv4']['address'] }}:9092"
  with_items: "{{kafka_list_topics_pfa}}"

**Comment by StephenSorriaux** [comment]
Hello,

I personally use this library on a daily basis with Kafka in version 2.1.1 so I don’t think it is related.
How did you configure your Kafka broker (listeners, advertised address, etc.)?

**Comment by chris93111** [comment]
all is default but i have try with 

listeners=PLAINTEXT://:$myip9092
advertised.listeners=PLAINTEXT://$myip:9092

**Comment by chris93111** [comment]
default is localhost and protocol PLAINTEXT

**Comment by ryarnyah** [comment]
Could you try adding:
```
import logging

log = logging.getLogger('kafka')
log.addHandler(logging.StreamHandler(sys.stdout))
log.setLevel(logging.INFO)
```

to get some logs?

**Comment by vldxlabs** [comment]
hello. i have same problem

ansible:
```
  - name: create acl
    kafka:
      resource: 'acl'
      api_version: "2.3.0"
      acl_resource_type: "topic"
      name: "*"
      acl_principal: "User:Anal"
      acl_operation: "all"
      acl_permission: "allow"
      state: "present"
      zookeeper: kafka.local:2181
      bootstrap_servers: kafka.local:9093
      security_protocol: 'SSL'
      ssl_check_hostname: true
      ssl_cafile: "{{ kafka.ssl.usersdir }}/ansible/CARoot.pem"
      ssl_certfile: "{{ kafka.users.ansible.cert }}"
      ssl_keyfile: "{{ kafka.users.ansible.key }}"
    tags: acl
```


kafka:
```
listeners=SSL://kafka.local:9093
advertised.listeners=SSL://kafka.local:9093
advertised.host.name=kafka.local
ssl.keystore.location=/opt/kafka/ssl/kafka.server.keystore.jks
ssl.keystore.password=4crndll2pm
ssl.key.password=4crndll2pm
ssl.truststore.location=/opt/kafka/ssl/kafka.server.truststore.jks
ssl.truststore.password=4crndll2pm
ssl.client.auth=required
listener.security.protocol.map=SSL:SSL
authorizer.class.name=kafka.security.auth.SimpleAclAuthorizer
super.users=User:CN=kafka.local;User:kafka;User:CN=ansible
allow.everyone.if.no.acl.found=false
security.inter.broker.protocol=SSL
```

netstat:
```
root@kafka:~# netstat -tulpan | grep -i listen|grep -P '(2181|9093)'
tcp6       0      0 10.254.242.241:9093     :::*                    LISTEN      23950/java      
tcp6       0      0 :::2181                 :::*                    LISTEN      21589/java  
```


```
root@kafka:~# grep -i endpoint /opt/kafka/kafka_2.12-2.3.0/logs/server.log|tail -1
[2019-10-01 14:03:30,093] INFO Registered broker 0 at path /brokers/ids/0 with addresses: ArrayBuffer(EndPoint(kafka.local,9093,ListenerName(SSL),SSL)), czxid (broker epoch): 337 (kafka.zk.KafkaZkClient)
```

**Comment by imvld** [comment]
hello. i have same problem
kafka_2.12-2.3.0

ansible:
```
  - name: create acl
    kafka:
      resource: 'acl'
      api_version: "2.3.0"
      acl_resource_type: "topic"
      name: "*"
      acl_principal: "User:Anal"
      acl_operation: "all"
      acl_permission: "allow"
      state: "present"
      zookeeper: kafka.local:2181
      bootstrap_servers: kafka.local:9093
      security_protocol: 'SSL'
      ssl_check_hostname: true
      ssl_cafile: "{{ kafka.ssl.usersdir }}/ansible/CARoot.pem"
      ssl_certfile: "{{ kafka.users.ansible.cert }}"
      ssl_keyfile: "{{ kafka.users.ansible.key }}"
    tags: acl
```


kafka:
```
listeners=SSL://kafka.local:9093
advertised.listeners=SSL://kafka.local:9093
advertised.host.name=kafka.local
ssl.keystore.location=/opt/kafka/ssl/kafka.server.keystore.jks
ssl.keystore.password=secret
ssl.key.password=secret
ssl.truststore.location=/opt/kafka/ssl/kafka.server.truststore.jks
ssl.truststore.password=secret
ssl.client.auth=required
listener.security.protocol.map=SSL:SSL
authorizer.class.name=kafka.security.auth.SimpleAclAuthorizer
super.users=User:CN=kafka.local;User:kafka;User:CN=ansible
allow.everyone.if.no.acl.found=false
security.inter.broker.protocol=SSL
```

netstat:
```
root@kafka:~# netstat -tulpan | grep -i listen|grep -P '(2181|9093)'
tcp6       0      0 10.254.242.241:9093     :::*                    LISTEN      23950/java      
tcp6       0      0 :::2181                 :::*                    LISTEN      21589/java  
```


```
root@kafka:~# grep -i endpoint /opt/kafka/kafka_2.12-2.3.0/logs/server.log|tail -1
[2019-10-01 14:03:30,093] INFO Registered broker 0 at path /brokers/ids/0 with addresses: ArrayBuffer(EndPoint(kafka.local,9093,ListenerName(SSL),SSL)), czxid (broker epoch): 337 (kafka.zk.KafkaZkClient)
```
but with python i can connect to kafka
