### ISSUE TITLE
Setting a PREFIXED ACL to absent has no effect

### ISSUE THREAD

**Issue by justCatchingRye** [StephenSorriaux/ansible-kafka-admin#61]
## Expected Behavior

Setting a PREFIXED ACL to absent results in the removal of the ACL entry

## Actual Behavior

The playbook runs AND reports that the ACL has been changed, but the ACL is **NOT** removed

## Play to Reproduce the Problem

```
- hosts: localhost
  gather_facts: false
  vars:
    api_version: "2.3.0"
    security_protocol: "PLAINTEXT"
    zookeeper: "locahost:2181"
    bootstrap_servers: "localhost:9092"
    test_permissions:
      - "describe"
  tasks:
    - name: Set ACL
      vars:
        # set vars for each task
        topic_name: "test.topic.prefix"
        topic_users:
          - "test.topic.user"
      with_nested:
        - "{{topic_name}}"
        - "{{topic_users}}"
        - "{{test_permissions}}"
      kafka_lib:
        # common configuration items
        api_version: "{{api_version}}"
        security_protocol: "{{security_protocol}}"
        zookeeper: "{{zookeeper}}"
        bootstrap_servers: "{{bootstrap_servers}}"
        # task configuration items
        resource: "acl"
        acl_resource_type: "topic"
        name: "{{item.0}}"
        acl_principal: "User:CN={{item.1}}"
        acl_operation: "{{item.2}}"
        acl_permission: "allow"
        acl_pattern_type: "prefixed"
        state: "absent"
```

## Logs from the play with Ansible in debug mode

```
ansible-playbook 2.8.5
  config file = None
  configured module search path = ['/Users/REDACTED/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.8.5/libexec/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.7.7 (default, Mar 10 2020, 15:43:33) [Clang 11.0.0 (clang-1100.0.33.17)]
No config file found; using defaults
setting up inventory plugins
host_list declined parsing /etc/ansible/hosts as it did not pass it's verify_file() method
script declined parsing /etc/ansible/hosts as it did not pass it's verify_file() method
auto declined parsing /etc/ansible/hosts as it did not pass it's verify_file() method
Parsed /etc/ansible/hosts inventory source with ini plugin
Loading callback plugin default of type stdout, v2.0 from /usr/local/Cellar/ansible/2.8.5/libexec/lib/python3.7/site-packages/ansible/plugins/callback/default.py

PLAYBOOK: create_acls.yml ***************************************************************************************************
Positional arguments: create_acls.yml
verbosity: 4
connection: smart
timeout: 10
become_method: sudo
tags: ('all',)
inventory: ('/etc/ansible/hosts',)
forks: 5
1 plays in create_acls.yml

PLAY [localhost] ************************************************************************************************************
META: ran handlers

TASK [Set ACL] **************************************************************************************************************
task path: /Users/REDACTED/data/work/mo/code/_workspace/msk/kafka/env-basic/create_acls.yml:12
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: REDACTED
<127.0.0.1> EXEC /bin/sh -c 'echo ~REDACTED && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/REDACTED/.ansible/tmp/ansible-tmp-1595494951.0280828-163312069815174 `" && echo ansible-tmp-1595494951.0280828-163312069815174="` echo /Users/REDACTED/.ansible/tmp/ansible-tmp-1595494951.0280828-163312069815174 `" ) && sleep 0'
Using module file /Users/REDACTED/.ansible/plugins/modules/ansible-kafka-admin/library/kafka_lib.py
<127.0.0.1> PUT /Users/REDACTED/.ansible/tmp/ansible-local-29952c31bfrig/tmp8km79jpl TO /Users/REDACTED/.ansible/tmp/ansible-tmp-1595494951.0280828-163312069815174/AnsiballZ_kafka_lib.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /Users/REDACTED/.ansible/tmp/ansible-tmp-1595494951.0280828-163312069815174/ /Users/REDACTED/.ansible/tmp/ansible-tmp-1595494951.0280828-163312069815174/AnsiballZ_kafka_lib.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/local/Cellar/ansible/2.8.5/libexec/bin/python3.7 /Users/REDACTED/.ansible/tmp/ansible-tmp-1595494951.0280828-163312069815174/AnsiballZ_kafka_lib.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /Users/REDACTED/.ansible/tmp/ansible-tmp-1595494951.0280828-163312069815174/ > /dev/null 2>&1 && sleep 0'
changed: [localhost] => (item=['test.topic.prefix', 'test.topic.user', 'describe']) => {
    "ansible_loop_var": "item",
    "changed": true,
    "invocation": {
        "module_args": {
            "acl_host": "*",
            "acl_operation": "describe",
            "acl_pattern_type": "prefixed",
            "acl_permission": "allow",
            "acl_principal": "User:CN=test.topic.user",
            "acl_resource_type": "topic",
            "api_version": "2.3.0",
            "bootstrap_servers": "localhost:9092",
            "name": "test.topic.prefix",
            "options": null,
            "partitions": 0,
            "replica_factor": 0,
            "resource": "acl",
            "sasl_kerberos_service_name": null,
            "sasl_mechanism": "PLAIN",
            "sasl_plain_password": null,
            "sasl_plain_username": null,
            "security_protocol": "PLAINTEXT",
            "ssl_cafile": null,
            "ssl_certfile": null,
            "ssl_check_hostname": true,
            "ssl_ciphers": null,
            "ssl_crlfile": null,
            "ssl_keyfile": null,
            "ssl_password": null,
            "ssl_supported_protocols": null,
            "state": "absent",
            "zookeeper": "locahost:2181",
            "zookeeper_auth_scheme": "digest",
            "zookeeper_auth_value": "",
            "zookeeper_max_retries": 5,
            "zookeeper_sleep_time": 5,
            "zookeeper_ssl_cafile": null,
            "zookeeper_ssl_certfile": null,
            "zookeeper_ssl_check_hostname": true,
            "zookeeper_ssl_keyfile": null,
            "zookeeper_ssl_password": null
        }
    },
    "item": [
        "test.topic.prefix",
        "test.topic.user",
        "describe"
    ],
    "msg": "acl 'test.topic.prefix': successfully deleted."
}
META: ran handlers
META: ran handlers

PLAY RECAP ******************************************************************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

**Result (no effect):**

```
$ kafka-acls.sh --authorizer-properties zookeeper.connect=$zookeeper --list
Current ACLs for resource `Topic:PREFIXED:test.topic.prefix`:
 	User:CN=test.topic.user has Allow permission for operations: Describe from hosts: *
```

## Specifications

```
- Library version: latest
- Result of `pip list` command: 
    kafka-python                 1.4.4
    kazoo                        2.6.1
    pure-sasl                    0.5.1
- Kafka version: kafka_2.12-2.3.0.jar
- Python version: 3.7.7
- OS: Darwin computer 19.5.0 Darwin Kernel Version 19.5.0: Thu Apr 30 18:25:59 PDT 2020; root:xnu-6153.121.1~7/RELEASE_X86_64 x86_64. Also seen with RHEL 7.7
```
