### ISSUE TITLE
Enhance installation & documentation

### ISSUE THREAD

**Issue by hinchliff** [StephenSorriaux/ansible-kafka-admin#69]
I'm not sure if I am misunderstanding how this library is supposed to be used, or if the documentation could be improved?

Why does this install as a Role?  How does one use it as a Module/Plugin?

## Expected Behavior
1. Install via `ansible-galaxy install -r requirements.yml --roles-path roles`
1. `pip install -r requirements.txt`
1. Use the `kafka_libs` module in playbook tasks from project top level. (Writing playbook tasks that use `kafka_libs` as the module. Not adding it as a Role in the playbook.)

## Actual Behavior
Above would result in
> ERROR! couldn't resolve module/action 'kafka_lib'. This often indicates a misspelling, missing collection, or incorrect module path.

If I manually moved/copied the module files, it seemed to work?
1. `mv ./roles/kafka_lib/library/* ./library/`
1. `mv ./roles/kafka_lib/module_utils ./plugins/`

But that seems like it may not be the best way?

## Specifications

  - Library version: 0.10.0
  - Result of `pip list` command: 
  - Kafka version:
  - Python version: Python 2.7.16
  - OS:

**Comment by hinchliff** [comment]
hmm... and the above doesn't quite work.  the location of `module_utils` must be wrong.
```
fatal: [redacted]: FAILED! => {"msg": "Could not find imported module support code for kafka_lib.  Looked for either ACLOperation.py or acl_operation.py"}
```

**Comment by StephenSorriaux** [comment]
Hello,

Yes the installation and usage are not that great.

Can you please precise:

- your Ansible version
- a reproductible playbook

FWIW, here my current playbook:
```yaml
- name: install Zookeeper, Kafka
  hosts: kafka, zookeeper
  roles:
    - name: kafka_lib
      tags: kafka
    - name: zookeeper
      tags: zookeeper
    - name: kafka
      tags: kafka
    - name: beats
      tags: beats
  post_tasks:
    - block:
      - delegate_to: 127.0.0.1
        run_once: true
        name: create topics
        kafka_lib:
          resource: "topic"
          api_version: "2.1.0"
          name: "{{ item.name }}"
          partitions: "{{ item.partitions }}"
          replica_factor: "{{ item.replica_factor }}"
          options: "{{ item.options | default(omit) }}"
          state: "{{ item.state }}"
          zookeeper: "{% for host in groups['zookeeper'] %}{{ hostvars[host]['ansible_host'] }}:2181{% if not loop.last %},{% endif %}{% endfor %}"
          bootstrap_servers: "{% for host in groups['kafka'] %}{{ hostvars[host]['ansible_host'] }}:{{ kafka_port }}{% if not loop.last %},{% endif %}{% endfor %}"
        with_items: "{{ kafka_topics }}"
      tags: topic

```
