### ISSUE TITLE
[Module] Create kafka_quotas module

### ISSUE THREAD

**Issue by ryarnyah** [StephenSorriaux/ansible-kafka-admin#86]
## Spec
Add module `kafka_quotas` to manage quotas on user, ip, ...

## Proposed module
```yaml
kafka_quotas:
  # classic kafka connection options
  ...
  entries:
  - entities:
     - entity_type: user # The entity type
       entity_name: test # The name of the entity, or null if the default
    quotas:
     - key: test # The quota configuration key
       value: 1 # The value to set, otherwise ignored if the value is to be removed
       state: present
```
