### ISSUE TITLE
[Module] Create kafka_configs module

### ISSUE THREAD

**Issue by ryarnyah** [StephenSorriaux/ansible-kafka-admin#87]
## Spec
A module to manage dynamics configurations

## Proposed module
```yaml
kafka_configs:
  # Classic configuration options
  ...
  configs:
  - resource_type: broker
    resource_name: test
    options:
      key: value
```
